server:
  port: 8888

logging:
  level:
    root: info
    org.springframework.cloud.config: debug

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amejid/microservices-demo-config-server-repo
          clone-on-start: true
          username: amejid
          password: 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
          default-label: main
      fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '{cipher}fb867cf99e7cbcdba6b4f48abf6f471af09a5007b6bdce65ebb51314003915eeb5369f306dd72be5ba991db812a7e101'

log:
  app-name: config-server